source 'https://github.com/CocoaPods/Specs.git'

#Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’
use_frameworks!


target 'BallClub' do

pod 'Moya-Gloss', :git => 'https://github.com/spxrogers/Moya-Gloss', :tag => '2.0.0-beta.3'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'Nuke', '~> 4.1.2'
pod 'AWSS3'
pod 'Fabric'
pod 'Crashlytics'
pod 'TextFieldEffects'
pod 'KeychainAccess'
pod 'IQKeyboardManagerSwift'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'GMStepper'
pod 'DZNEmptyDataSet'
pod 'Popover'
pod 'Mixpanel-swift'
pod 'DropDown'
pod 'DZNEmptyDataSet'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
